/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contact {
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "org_id")]
    pub org_id: String,
}

impl Contact {
    pub fn new(first_name: String, id: String, last_name: String, org_id: String) -> Contact {
        Contact {
            first_name,
            id,
            last_name,
            org_id,
        }
    }
}

