/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyReqPayload {
    /// The name which will be assigned to the new api key.
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateApiKeyReqPayload {
    pub fn new(name: String) -> CreateApiKeyReqPayload {
        CreateApiKeyReqPayload {
            name,
        }
    }
}

