/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Invitation {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "role")]
    pub role: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "used")]
    pub used: bool,
}

impl Invitation {
    pub fn new(created_at: String, email: String, id: uuid::Uuid, organization_id: String, role: i32, updated_at: String, used: bool) -> Invitation {
        Invitation {
            created_at,
            email,
            id,
            organization_id,
            role,
            updated_at,
            used,
        }
    }
}

