/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Link {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "org_id")]
    pub org_id: String,
}

impl Link {
    pub fn new(id: String, link: String, org_id: String) -> Link {
        Link {
            id,
            link,
            org_id,
        }
    }
}

