/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTaskResourceResponse {
    ListTaskResourceResponseOneOf(Box<models::ListTaskResourceResponseOneOf>),
    ListTaskResourceResponseOneOf1(Box<models::ListTaskResourceResponseOneOf1>),
    ListTaskResourceResponseOneOf2(Box<models::ListTaskResourceResponseOneOf2>),
}

impl Default for ListTaskResourceResponse {
    fn default() -> Self {
        Self::ListTaskResourceResponseOneOf(Default::default())
    }
}

