/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Phone {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "org_id")]
    pub org_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Phone {
    pub fn new(created_at: String, id: String, number: String, org_id: String, updated_at: String) -> Phone {
        Phone {
            created_at,
            id,
            number,
            org_id,
            updated_at,
        }
    }
}

