/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TaskResource {
    TaskResourceOneOf(Box<models::TaskResourceOneOf>),
    TaskResourceOneOf1(Box<models::TaskResourceOneOf1>),
    TaskResourceOneOf2(Box<models::TaskResourceOneOf2>),
}

impl Default for TaskResource {
    fn default() -> Self {
        Self::TaskResourceOneOf(Default::default())
    }
}

