/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskResType {
    #[serde(rename = "link")]
    Link,
    #[serde(rename = "deal")]
    Deal,
    #[serde(rename = "user")]
    User,

}

impl ToString for TaskResType {
    fn to_string(&self) -> String {
        match self {
            Self::Link => String::from("link"),
            Self::Deal => String::from("deal"),
            Self::User => String::from("user"),
        }
    }
}

impl Default for TaskResType {
    fn default() -> TaskResType {
        Self::Link
    }
}

