/*
 * Trieve API
 *
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developers@trieve.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskResourceOneOf1 {
    #[serde(rename = "deal")]
    pub deal: Box<models::TaskDeal>,
}

impl TaskResourceOneOf1 {
    pub fn new(deal: models::TaskDeal) -> TaskResourceOneOf1 {
        TaskResourceOneOf1 {
            deal: Box::new(deal),
        }
    }
}

